twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        adresse_mail: 'dokkanbattlefrancecontact@gmail.com'
        copyright: 'Copyright © 2021 - Cédric Martin'
        contact: 'Contact'
    form_themes : ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true
